ARG DOCKER_BASE_IMAGE=lentychang/gazebo:base
FROM $DOCKER_BASE_IMAGE
ARG ROS_DISTRO=melodic

RUN cd /root && \
    apt-get update && \
    apt-get install -y libxss1 libxss-dev && \
    wget -c https://go.microsoft.com/fwlink/?LinkID=760868 -O vscode.deb


RUN cd /root && \
    dpkg -i vscode.deb || true && \
    apt -f install -y && \
    dpkg -i vscode.deb  && \
    rm vscode.deb

RUN ./usr/bin/python -m pip install -U flake8 --user

