version: '2' 
services:

  ros-base_local:
    image: ros-docker-base
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: roscore

  gazebo_local:
    image: gazebo:latest
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime:ro
      - $HOME/.Xauthority:/root/.Xauthority
      - $HOME/src/sim_device:/root/catkin_ws/src/sim_device
      - $HOME/src/all_msgs:/root/catkin_ws/src/all_msgs 
      - $HOME/.config/Code/User/settings.json:/root/.config/Code/User/settings.json
      - $HOME/.vscode/extensions:/root/.vscode/extensions   
      # - $HOME/Dropbox/IWT/src/test/urdf_tutorial:/root/catkin_ws/src/urdf_tutorial
      #- /run/nvidia:/run/nvidia:shared
      # - nvidia_driver_384.130:/usr/local/nvidia:ro
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: tail -f /dev/null
    # command: ["/bin/bash", "-exec", "-c","source ~/catkin_ws/devel/setup.bash && roslaunch --wait thesis thesis_gazebo.launch"]

  moveit_local:
    image: moveit:latest
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
     # ROS_IP: localhost
     # ROS_MASTER_URI: "http://localhost:11311"
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true 
    network_mode: host 
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
      - $HOME/src/all_msgs:/root/catkin_ws/src/all_msgs 
      - $HOME/src/sim_device:/root/catkin_ws/src/sim_device
      - $HOME/src/sim_device/thesis_moveit_config/config/moveit.rviz:/root/.rviz/default.rviz
      - $HOME/.config/Code/User/settings.json:/root/.config/Code/User/settings.json
      - $HOME/.vscode/extensions:/root/.vscode/extensions   
    #  - nvidia_driver_384.130:/usr/local/nvidia:ro
    privileged: true 
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true 
    command: tail -f /dev/null
    # command: ["/bin/bash", "-exec", "-c","source ~/catkin_ws/devel/setup.bash && sleep 5 && roslaunch --wait thesis_moveit_config moveit_planning_execution.launch"]

  pcl_local:
    image: pcl:latest
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
      - $HOME/src/ros_pcl:/root/catkin_ws/src/ros_pcl
      - $HOME/src/all_msgs:/root/catkin_ws/src/all_msgs 
      - $HOME/.config/Code/User/settings.json:/root/.config/Code/User/settings.json
      - $HOME/.vscode/extensions:/root/.vscode/extensions
    privileged: true
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: tail -f /dev/null
    # command: ["/bin/bash", "-exec", "-c","source ~/catkin_ws/devel/setup.bash && roslaunch --wait ros_pcl dataProcessing.launch"]

  pythonocc_local:
    image: pythonocc:latest
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true 
    network_mode: host 
    volumes:
      - $HOME/exchange:/root/exchange
      - $HOME/Volume/pythonocc_example:/root/pythonocc_example
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /usr/share/fonts/:/usr/share/fonts
      - $HOME/src/all_msgs:/root/catkin_ws/src/all_msgs 
      - $HOME/src/rel_pose_ext:/root/catkin_ws/src/rel_pose_ext
    privileged: true 
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true 
    command: tail -f /dev/null


#version: '2'
#volumes:
#  nvidia_driver_384.130:
#    external: true
