version: '2.3' 
services:

  ros-base:
    image: lentychang/ros-base:melodic
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: roscore

  gazebo:
    image: lentychang/gazebo:latest
    depends_on:
      - ros-base
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    # command: tail -f /dev/null
    command: ["/bin/bash","-exec","-c","source /root/catkin_ws/devel/setup.bash && roslaunch thesis thesis.launch"]

  moveit :
    image: lentychang/gazebo:latest
    depends_on:
      - ros-base
      - gazebo
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
     # ROS_IP: localhost
     # ROS_MASTER_URI: "http://localhost:11311"
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true 
    network_mode: host 
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
      - $HOME/catkin_ws/src/thesis/sim_device/thesis_moveit_config/config/moveit.rviz:/root/.rviz/default.rviz
    privileged: true 
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true 
    # command: tail -f /dev/null
    command: ["/bin/bash", "-exec", "-c","source ~/catkin_ws/devel/setup.bash && sleep 5 && roslaunch --wait thesis_moveit_config thesis_rviz_movit.launch & source ~/catkin_ws/devel/setup.bash && sleep 5 && roslaunch thesis_visualization thesis_visualization.launch"]
    # command: ["/bin/bash", "-exec", "-c","head /root/catkin_ws/src/sim_device/thesis_visualization/src/addVisualModelNode.py"]
    
    #  pcl:
    #    image: pcl:latest
    #    depends_on:
    #      - ros-base
    #      - gazebo
    #    environment:
    #      ROS_IP: $ROS_IP
    #      ROS_MASTER_URI: $ROS_MASTER_URI
    #      DISPLAY: :0
    #      QT_X11_NO_MITSHM: '1'
    #    stdin_open: true
    #    network_mode: host
    #    volumes:
    #      - $HOME/exchange:/root/exchange
    #      - /tmp/.X11-unix:/tmp/.X11-unix
    #      - $HOME/.Xauthority:/root/.Xauthority
    #      - /etc/localtime:/etc/localtime:ro
    #      - $HOME/src/thesis/all_msgs:/root/catkin_ws/src/all_msgs
    #      - $HOME/src/thesis/v4r:/root/v4r
    #      - $HOME/src/thesis/ros_pcl:/root/catkin_ws/src/ros_pcl
    #    privileged: true
    #    devices:
    #    - /dev/bus/usb:/dev/bus/usb
    #    tty: true
    #    # command: tail -f /dev/null
    #    command: ["/bin/bash", "-exec", "-c","source ~/catkin_ws/devel/setup.bash && sleep 10 && roslaunch --wait ros_pcl dataProcessing.launch"]


  pythonocc:
    image: lentychang/pythonocc:latest
    depends_on:
        - moveit
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
      # in order to run python3 from conda
      PATH: '/root/miniconda/envs/pythonocc/bin:$PATH'
    stdin_open: true 
    network_mode: host 
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /usr/share/fonts/:/usr/share/fonts
      - $HOME/src/thesis/all_msgs:/root/catkin_ws/src/all_msgs
      - $HOME/src/thesis/rel_pose_ext:/root/catkin_ws/src/rel_pose_ext
    privileged: true 
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true 
    # command: tail -f /dev/null
    command: ["/bin/bash", "-exec", "-c", ". ~/.bashrc && source ~/catkin_ws/devel/setup.bash && roslaunch rel_pose_ext alignedModelPublisher.launch"]
