version: '2' 
services:

  ros-base:
    image: ros-docker-base
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: roscore

  gazebo:
    image: gazebo:latest
    depends_on:
      - ros-base
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - $HOME/Dropbox/IWT/src/sim_device:/root/catkin_ws/src/sim_device
        # - $HOME/Dropbox/IWT/src/thesis:/root/catkin_ws/src/thesis
      - /etc/localtime:/etc/localtime:ro
        # for old nvidia-docker version 1
        # - /run/nvidia:/run/nvidia:shared
        # - nvidia_driver_384.130:/usr/local/nvidia:ro
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    tty: true
    # command: tail -f /dev/null
    command: ["/bin/bash", "-exec", "-c","source ~/catkin_ws/devel/setup.bash && roslaunch --wait thesis thesis_gazebo.launch"]

  moveit :
    image: moveit:latest
    depends_on:
      - ros-base
      - gazebo
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
     # ROS_IP: localhost
     # ROS_MASTER_URI: "http://localhost:11311"
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true 
    network_mode: host 
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
      - $HOME/Dropbox/IWT/src/sim_device:/root/catkin_ws/src/sim_device
        # - $HOME/Dropbox/IWT/src/thesis:/root/catkin_ws/src/thesis
      - $HOME/Dropbox/IWT/src/sim_device/thesis_moveit_config/config/moveit.rviz:/root/.rviz/default.rviz
    privileged: true 
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true 
    # command: tail -f /dev/null
    command: ["/bin/bash", "-exec", "-c","source ~/catkin_ws/devel/setup.bash && sleep 5 && roslaunch --wait thesis_moveit_config thesis_rviz_movit.launch & source ~/catkin_ws/devel/setup.bash && sleep 12 && roslaunch thesis_visualization fakeRecognition.launch"]

  pcl:
    image: pcl:latest
    depends_on:
      - ros-base
      - gazebo
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/lenty/Dropbox/IWT/src/v4r:/root/v4r                                         
      - /home/lenty/Dropbox/IWT/src/ros_pcl:/root/catkin_ws/src/ros_pcl
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true
    # command:
    command: ["/bin/bash", "-exec", "-c","source ~/catkin_ws/devel/setup.bash && roslaunch --wait ros_pcl dataProcessing.launch"]


  pythonocc:
    image: pythonocc:latest
    environment:
      ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true 
    network_mode: host 
    volumes:
      - $HOME/exchange:/root/exchange
      - $HOME/Volume/pythonocc_example:/root/pythonocc_example
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /usr/share/fonts/:/usr/share/fonts
      - $HOME/Dropbox/IWT/src/rel_pose_ext:/root/catkin_ws/src/rel_pose_ext
    privileged: true 
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true 
    command: tail -f /dev/null


#version: '2'
#volumes:
#  nvidia_driver_384.130:
#    external: true
