version: '2'
services:
  pcl_ros :
    image: pcl:ros
    environment:
     # ROS_IP: $ROS_IP
      ROS_MASTER_URI: $ROS_MASTER_URI
      DISPLAY: :0
      QT_X11_NO_MITSHM: '1'
    stdin_open: true
    network_mode: host
    volumes:
      - $HOME/exchange:/root/exchange
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /home/lenty/Dropbox/IWT/src/v4r:/root/v4r
      - /home/lenty/Dropbox/IWT/src/ros_pcl:/root/catkin_ws/src/ros_pcl
      - $HOME/.Xauthority:/root/.Xauthority
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    devices:
    - /dev/bus/usb:/dev/bus/usb
    tty: true
    command: tail -f /dev/null

