ARG DOCKER_BASE_IMAGE=moveit:ide
FROM $DOCKER_BASE_IMAGE
ARG ROS_DISTRO=kinetic

RUN cd ~/catkin_ws/src && \
    git clone https://github.com/lentychang/all_msgs && \
    git clone https://github.com/lentychang/sim_device.git

RUN cd ~/catkin_ws && source devel/setup.bash && \
    catkin_make

RUN echo "source /root/catkin_ws/devel/setup.bash" >> ~/.bashrc && \
    echo "export PS1='\[\e[1;32m\]MoveIt\[\e[m\e[1;39m\]@\[\e[m\e[1;36m\]\h \[\e[1;34m\]\W\[\e[m\]$ '" >> ~/.bashrc
